language: php
php:
  - 5.3
before_script:
  - wget http://sourceforge.net/projects/simpletest/files/simpletest/simpletest_1.1/simpletest_1.1.0.tar.gz/download
  - tar -xvzf simpletest_1.1.0.tar.gz
  - phpenv rehash
script: php test/run-tests.php
