language: php
php:
  - 5.3
before_script:
  - wget http://downloads.sourceforge.net/project/simpletest/simpletest/simpletest_1.1/simpletest_1.1.0.tar.gz
  - tar -xvzf simpletest_1.1.0.tar.gz
  - phpenv rehash
script: php test/run-tests.php
